apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xbackuppolicys.example.crossplane.io
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1alpha1
    kind: XBackupPolicy
  mode: Pipeline
  pipeline:
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready


